export const CELL_WIDTH = 2
export const ANSI_RESET = '\x1b[0m'
export const ANSI_TEXT = '\x1b[36m'
export const ANSI_IS = '\x1b[33m'
export const GRAPHEME_SEGMENTER = new Intl.Segmenter('en', {
  granularity: 'grapheme',
})

export const OBJECT_GLYPHS: Record<string, string> = {
  algae: '🪸',
  baba: '🐑',
  brick: '🟧',
  crab: '🦀',
  ice: '🧊',
  jelly: '🍮',
  flag: '🚩',
  lava: '🌋',
  wall: '🧱',
  rock: '🪨',
  seastar: '⭐',
  skull: '💀',
  tile: '🟫',
  water: '🌊',
  keke: '🐸',
  bug: '🐞',
  door: '🚪',
  key: '🔑',
  flower: '🌸',
  grass: '🌿',
  moon: '🌙',
  star: '⭐',
  tree: '🌳',
  belt: '🧵',
}

export const TEXT_CODES: Record<string, string> = {
  baba: 'BA',
  flag: 'FL',
  wall: 'WA',
  rock: 'RO',
  water: 'WT',
  keke: 'KE',
  bug: 'BU',
  door: 'DO',
  key: 'KY',
  flower: 'FW',
  grass: 'GR',
  moon: 'MO',
  star: 'SR',
  tree: 'TR',
  belt: 'BE',
  text: 'TX',
  is: 'IS',
  you: 'YO',
  win: 'WI',
  stop: 'SP',
  push: 'PU',
  move: 'MV',
  open: 'OP',
  shut: 'SH',
  float: 'FT',
  tele: 'TL',
  pull: 'PL',
  shift: 'SF',
  swap: 'SW',
  up: 'UP',
  right: 'RT',
  down: 'DN',
  left: 'LF',
  and: 'AN',
  has: 'HA',
  not: 'NO',
  empty: 'EM',
  red: 'RD',
  blue: 'BL',
  best: 'BS',
  defeat: 'DE',
  sink: 'SI',
  hot: 'HO',
  melt: 'ME',
  weak: 'WK',
}
