export const BOARD3D_POSTFX_CONFIG = {
  MAX_DEVICE_PIXEL_RATIO: 1.4,
  POSTFX_PIXEL_RATIO_SCALE: 1,
  BLOOM_RESOLUTION_SCALE: 0.65,
  BLOOM_DENSE_TEXT_RESOLUTION_SCALE: 0.84,
  BOKEH_ENABLE_MARGIN: 1.12,
  BLOOM_INITIAL_RESOLUTION_X: 1,
  BLOOM_INITIAL_RESOLUTION_Y: 1,
  BOKEH_INITIAL_FOCUS: 10,
  BOKEH_FOCUS_MIN: 4,
} as const
