export const BOARD3D_CARD_TEXTURE_CONFIG = {
  CARD_TEXTURE_SIZE: 256,
  EMOJI_CARD_TEXTURE_SIZE: 512,
  CARD_TEXTURE_PAD_RATIO: 0.08,
  CARD_TEXTURE_EMOJI_FONT_RATIO: 0.9,
  // Labels auto-fit the card: font size = fill ratio of the content box,
  // capped so short words stay punchy without long words bleeding off.
  CARD_TEXTURE_TEXT_MAX_FONT_SIZE: 108,
  CARD_TEXTURE_TEXT_FILL_RATIO: 0.88,
  CARD_TEXTURE_LABEL_OFFSET_Y: 4,
  CARD_TEXTURE_TEXT_STROKE_WIDTH_RATIO: 0.05,
  CARD_TEXTURE_EMOJI_FONT_FAMILY:
    '"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif',
  CARD_TEXTURE_TEXT_FONT_FAMILY:
    '"Trebuchet MS","Arial Rounded MT Bold","Segoe UI Emoji",sans-serif',
  CARD_TEXTURE_DIRECTION_FONT_RATIO: 0.36,
  CARD_TEXTURE_DIRECTION_EDGE_INSET_RATIO: 0.12,
  CARD_TEXTURE_DIRECTION_OFFSET_Y: 1,
} as const

export const BOARD3D_SHADOW_TEXTURE_CONFIG = {
  SHADOW_TEXTURE_SIZE: 128,
  SHADOW_TEXTURE_CENTER: 64,
  SHADOW_TEXTURE_INNER_RADIUS: 17,
  SHADOW_TEXTURE_OUTER_RADIUS: 50,
  SHADOW_TEXTURE_STOP_0: 'rgba(0, 0, 0, 0.25)',
  SHADOW_TEXTURE_STOP_1: 'rgba(0, 0, 0, 0.09)',
  SHADOW_TEXTURE_STOP_2: 'rgba(0, 0, 0, 0)',
  SHADOW_TEXTURE_STOP_1_AT: 0.48,
} as const
