import { CAMERA_TILT_FROM_VERTICAL_RAD_BASE } from './board-3d-config-camera.js'

export const BOARD3D_LIGHTING_CONFIG = {
  LIGHT_HEIGHT_Y_BASE: 9.2,
  LIGHT_HEIGHT_Y_SPAN_MUL: 0.84,
  SIDE_LIGHT_OFFSET_X_BASE: 3.4,
  SIDE_LIGHT_OFFSET_X_MUL: 0.36,
  SIDE_LIGHT_OFFSET_Z_BASE: 2.4,
  SIDE_LIGHT_OFFSET_Z_MUL: 0.28,
  LIGHT_CAMERA_SIDE_TILT_RAD: CAMERA_TILT_FROM_VERTICAL_RAD_BASE,
  AMBIENT_LIGHT_COLOR: '#f3f5ff',
  AMBIENT_LIGHT_INTENSITY_MUL: 1.135,
  SIDE_LIGHT_INTENSITY_MIN: 0.67,
  SIDE_LIGHT_INTENSITY_MUL: 0.9125,
  SIDE_LIGHT_INITIAL_Y: 10,
  SIDE_LIGHT_INITIAL_Z: 6,
  LIGHT_SHADOW_CAMERA_NEAR: 0.1,
  LIGHT_SHADOW_BIAS: -0.00006,
  LIGHT_SHADOW_NORMAL_BIAS: 0.04,
  LIGHT_HEIGHT_Y_EXTRA: 4.6,
  LIGHT_DROP_Y_MIN: 0.5,
  LIGHT_DROP_Y_SUB: 0.08,
  LIGHT_TARGET_Y: 0.08,
} as const
